---

mapr_client_servers:
  hosts: [ mclient1.lan, mclient2.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
all:
  children: [ mapr_client_servers ]
_meta:
  hostvars:
    mclient1.lan:
      vagrant_cpu: "1"
      vagrant_mem: "4096"
    mclient2.lan:
      vagrant_cpu: "1"
      vagrant_mem: "4096"